[package]
name = "dropblog"
version = "1.0.0"
authors = ["Richard Dallaway <richard@dallaway.com>"]
edition = "2018"

[dependencies]
imap = "1.0.2"
native-tls = "0.2.3" 
mailparse = "0.10.2"
structopt = "0.3"
clap = "2.33"
chrono = "0.4.10"
tempfile = "3.1.0"
slug = "0.1"