[package]
name = "dropblog"
version = "2.0.2"
authors = ["Richard Dallaway <richard@dallaway.com>"]
edition = "2021"

[dependencies]
structopt = "0.3"
imap = "2.4"
native-tls = "0.2" 
mailparse = "0.13"
regex = "1.3"
chrono = "0.4"
slug = "0.1"
reqwest = { version = "0.11", features=["json", "blocking"] }
http = "0.2"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"