[package]
name = "dropblog"
version = "1.0.0"
authors = ["Richard Dallaway <richard@dallaway.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
clap = "2.33"
imap = "1.0.2"
native-tls = "0.2.3" 
mailparse = "0.10.2"
regex = "1.3"
chrono = "0.4.10"
slug = "0.1"
reqwest = { version = "0.10", features=["blocking"] }
http = "0.2"
thiserror = "1.0"